### ISSUE TITLE
Resolve CORS policy error for plot.glb

### ISSUE THREAD

**Issue by abhishekrathi16** [TechnocultureResearch/VVplus#4]

**Comment by sutyum** [comment]
kindly add screenshots and any other useful info to description @abhishekrathi16

**Comment by abhishekrathi16** [comment]
Here are some screenshots related to the issue. The problem is occurring only in the plot.glb/plot.gltf files and all other files are working fine. It also seems to be working sometimes in chrome when in development, but never in firefox, and does not seem to work in the preview deployment by Vercel.

![err9](https://user-images.githubusercontent.com/82315852/188480176-4aa8aed7-8607-490c-b011-138a56d66189.png)
![err10](https://user-images.githubusercontent.com/82315852/188480179-5870aa7b-2546-4679-ad5d-dd24a4e7045a.png)
![error11](https://user-images.githubusercontent.com/82315852/188480181-09f1470f-ca1a-4848-81d3-29c7f0c4b076.png)

**Comment by sutyum** [comment]
I have resolved this issue by adding the appropriate settings on the CDN currently in use on the backend (AWS CloudFront). Kindly let me know if I can close this issue. @abhishekrathi16

**Comment by abhishekrathi16** [comment]
Yes, the issue has been resolved. No errors are being faced on the frontend side. You can close the issue now. @sutyum
